### ISSUE TITLE
Can not open or extract the "sessions" file

### ISSUE THREAD

**Issue by ARVIN-B** [EternalC0der/TeleShadow3#2]
Can not open or extract the "sessions" file
It says that "file corrupted".
What I must do?!?!

**Comment by EternalC0der** [comment]
Hi,
Are you using the latest version of winrar ?

**Comment by ARVIN-B** [comment]
hi
yes

**Comment by EternalC0der** [comment]
Hi,
In the next update I'm going to use zip instead of rar archives. So it would be more compatible.
Thanks for your patience.

**Comment by bad0cash** [comment]
Hello. Have you updated the program? Just files that are still corrupted are sent
