### ISSUE TITLE
Cannot connect to remote server

### ISSUE THREAD

**Issue by erfze** [EternalC0der/TeleShadow3#3]
![image](https://user-images.githubusercontent.com/38813661/95855379-e09d8680-0d8a-11eb-938e-83bb95217f6e.png)
What is a remote server？

**Comment by EternalC0der** [comment]
Hi,
Make sure your proxy server and port are correct.
Also, it has to be an HTTP proxy server. Good luck :)

**Comment by Disorden456** [comment]
I used HTTP paid proxies and still not working for me, when using Gmail API (with less secure apps ) google still blocks login from a different device,

**Comment by EternalC0der** [comment]
Hello,
HTTP Proxies are used for Telegram API transport option because Telegram it is blocked in some countries (eg. Iran)
So for your issue about Gmail API, you should allow less secured apps in your Gmail settings.
And please, open a new issue if your problem persists.

**Comment by Disorden456** [comment]
thankyou for replying, I have allowed less secure apps,  what If I use payload only in telegram allowed countries can I use API without proxy?  I tried building payload without using a proxy, but the payload doesn't work

**Comment by EternalC0der** [comment]
Sure,
You can leave Proxy IP and Proxy Port empty,
I'm not sure if Teleshadow's payload is still working, but you can edit the payload.cs and build it manually to get it to work

**Comment by el3ktraz** [comment]
payload worked with Gmail on my device and provided the session rar, but copy-pasting it didn't give account, without proxy payload didn't work for me, and I don't know c# properly, anyways thank you soo much for you're help.
